### ISSUE TITLE
Sample not working 

### ISSUE THREAD

**Issue by prashanthmadi** [Azure-Samples/azure-cosmos-db-mongodb-spring#7]
This sample is not working anymore. please refer below
https://github.com/prashanthmadi/cosmosdb-mongodb-readpreference-springboot-java/blob/main/src/main/java/azure/cosmosdb/mongodb/spring/cosmosdbmongodb/ApplicationConfig.java

**Comment by seesharprun** [comment]
A new sample is coming later today, thanks for reporting this!
